spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/terrier
    username: user
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    