spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/terrier
    username: user
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  mvc:
    converters:
      preferred-json-mapper: jackson
logging:
  pattern:
    level: "%replace(xrid:%X{XRID} ){'xrid: ',''}%replace(xsid:%X{XSID} ){'xsid: ',''}%5p"
  level:
    root: info
schedulers:
  datasource:
    pool-size: 100
    queue-task-cap: 500

cors:
  allowed-origins:
    - http://localhost:3000
admin.users:
  - login: user
    password: "$2a$12$BMfXJWpJvluMUy89bQuA1uV0YbNmiYdhasxNz3ahCEE4wIcoc8XOS"
payments.square:
  access-token: my-access-token
  environment: SANDBOX
  currency: EUR
  