spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/terrier
    username: user
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  mvc:
    converters:
      preferred-json-mapper: jackson
  mail:
    host: smtp.gmail.com
    port: 587
    username: myemail@gmail.com
    password: mypassword
    properties.mail.smtp:
      auth: true
      starttls.enable: true
logging:
  pattern:
    level: "%replace(xrid:%X{XRID} ){'xrid: ',''}%replace(xsid:%X{XSID} ){'xsid: ',''}%5p"
  level:
    root: info
schedulers:
  datasource:
    pool-size: 100
    queue-task-cap: 500
  payment:
    pool-size: 10
    queue-task-cap: 10

cors:
  allowed-origins:
    - http://localhost:3000
admin.users:
  - login: user
    password: "$2a$12$BMfXJWpJvluMUy89bQuA1uV0YbNmiYdhasxNz3ahCEE4wIcoc8XOS"
payments:
  tva-percentage: 10
  down-payment-ratio: 0.30
  cleaning-fee-cents: 20000
  due-date-min-delay-days: 30
  reminder-days: -7
  reminder-message: 'Bonjour,\n
    Merci d''avoir réservé votre séjour avec nous. \n
    Vous recevez ce rappel pour réaliser le paiement final de votre réservation \n
    \n 
    A bientôt au Terrier ! \n
  '
  square:
    access-token: my-access-token
    environment: SANDBOX
    currency: EUR
    location-id: LocationId
notification:
  email: leterrier-gites@gmail.com
discord:
  client:
    login: discord-login
    password: discord-password
    channel-id: channel-id